# ========================================
# Sync Docker Hub README
# Automatically updates Docker Hub overview from repository
# ========================================
#
# Triggers:
#   - Push to main branch (only if DOCKER_HUB_README.md changes)
#   - Manual workflow dispatch
#   - After docker images are published
#
# Required Secrets:
#   DOCKERHUB_USERNAME - Docker Hub username
#   DOCKERHUB_TOKEN    - Docker Hub access token
#
# ========================================

name: Sync Docker Hub README

on:
  push:
    branches:
      - main
    paths:
      - 'docs/DOCKER_HUB_README.md'
  workflow_dispatch:  # Allow manual trigger
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

jobs:
  sync-backend-readme:
    name: Sync Backend README
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Update Docker Hub Backend Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lbrines/classsphere-backend
          readme-filepath: ./docs/DOCKER_HUB_README.md
          short-description: 'Educational platform with Google Classroom integration - Backend (Go 1.24.7 + Echo v4)'
      
      - name: Summary
        run: |
          echo "✅ Backend README synced to Docker Hub"
          echo "📦 Repository: lbrines/classsphere-backend"
          echo "🔗 URL: https://hub.docker.com/r/lbrines/classsphere-backend"

  sync-frontend-readme:
    name: Sync Frontend README
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Update Docker Hub Frontend Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lbrines/classsphere-frontend
          readme-filepath: ./docs/DOCKER_HUB_README.md
          short-description: 'Educational platform with Google Classroom integration - Frontend (Angular 19 + Nginx)'
      
      - name: Summary
        run: |
          echo "✅ Frontend README synced to Docker Hub"
          echo "📦 Repository: lbrines/classsphere-frontend"
          echo "🔗 URL: https://hub.docker.com/r/lbrines/classsphere-frontend"

  notify-completion:
    name: Notify Completion
    runs-on: ubuntu-latest
    needs: [sync-backend-readme, sync-frontend-readme]
    
    steps:
      - name: Summary
        run: |
          echo "🎉 Docker Hub README sync completed successfully!"
          echo ""
          echo "📦 Backend:  https://hub.docker.com/r/lbrines/classsphere-backend"
          echo "📦 Frontend: https://hub.docker.com/r/lbrines/classsphere-frontend"
          echo ""
          echo "✅ Both repositories now have updated overviews"

